// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3HOgye1ogigGuxZv1q2ifln9f0WpksOY',
    appId: '1:672975519643:web:d17ccbd7481d0d6d2feb3e',
    messagingSenderId: '672975519643',
    projectId: 'traan-f9e6a',
    authDomain: 'traan-f9e6a.firebaseapp.com',
    storageBucket: 'traan-f9e6a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcNNnXhWbKFISzf4TNZBKXw7pMGYvqaZQ',
    appId: '1:672975519643:android:5be74c1e1a7d12b02feb3e',
    messagingSenderId: '672975519643',
    projectId: 'traan-f9e6a',
    storageBucket: 'traan-f9e6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6ptDXr5zswELgdpl_P37BdNbTRhs0RZ8',
    appId: '1:672975519643:ios:d16c0be53e4295832feb3e',
    messagingSenderId: '672975519643',
    projectId: 'traan-f9e6a',
    storageBucket: 'traan-f9e6a.firebasestorage.app',
    iosClientId: '672975519643-nm5sl4k2ugdobmr4df3l08r23klfl3qs.apps.googleusercontent.com',
    iosBundleId: 'com.example.raksha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6ptDXr5zswELgdpl_P37BdNbTRhs0RZ8',
    appId: '1:672975519643:ios:d16c0be53e4295832feb3e',
    messagingSenderId: '672975519643',
    projectId: 'traan-f9e6a',
    storageBucket: 'traan-f9e6a.firebasestorage.app',
    iosClientId: '672975519643-nm5sl4k2ugdobmr4df3l08r23klfl3qs.apps.googleusercontent.com',
    iosBundleId: 'com.example.raksha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3HOgye1ogigGuxZv1q2ifln9f0WpksOY',
    appId: '1:672975519643:web:c5cf07566334b3f42feb3e',
    messagingSenderId: '672975519643',
    projectId: 'traan-f9e6a',
    authDomain: 'traan-f9e6a.firebaseapp.com',
    storageBucket: 'traan-f9e6a.firebasestorage.app',
  );

}